apiVersion: v1
kind: Pod
metadata:
  name: hello1
  labels:
    app: myapp
spec:
  containers:
  - name: hello1-container
    image: busybox
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 36']